"""``Conversation`` / ``Message`` (``app/models/conversation.py``) match the design in
``docs/design/db-design.md``, and the first Alembic revision creates exactly what the models
declare — checked offline against the SQL Server dialect, no database.
"""

from __future__ import annotations

import io
import logging
import re
from pathlib import Path

import pyodbc
import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy.dialects import mssql
from sqlalchemy.schema import CreateIndex, CreateTable

import app.models
from app.db.base import Base
from app.models import Conversation, Message
from app.models.conversation import DEFAULT_TITLE, TITLE_MAX_LENGTH

INI = Path(__file__).resolve().parents[1] / "alembic.ini"
TEST_URL = (
    "mssql+aioodbc://u:p@db.invalid:1433/app"
    "?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=no"
)
DIALECT = mssql.dialect()


def _ddl(table_name: str) -> str:
    return str(CreateTable(Base.metadata.tables[table_name]).compile(dialect=DIALECT))


def _normalise(sql: str) -> str:
    return re.sub(r"\s+", " ", sql).strip()


def test_models_are_registered_for_alembic() -> None:
    assert {"conversations", "messages"} <= set(Base.metadata.tables)
    assert set(app.models.__all__) == {"Conversation", "Message"}


def test_conversations_columns() -> None:
    ddl = _ddl("conversations")
    assert "id UNIQUEIDENTIFIER NOT NULL" in ddl
    assert f"title NVARCHAR({TITLE_MAX_LENGTH}) NOT NULL" in ddl
    assert "created_at DATETIME2(3) NOT NULL DEFAULT sysutcdatetime()" in ddl
    assert "updated_at DATETIME2(3) NOT NULL DEFAULT sysutcdatetime()" in ddl
    assert "CONSTRAINT pk_conversations PRIMARY KEY (id)" in ddl


def test_conversations_have_no_owner_until_auth() -> None:
    # ADR-0013: conversations are shared until Okta lands.
    assert set(Base.metadata.tables["conversations"].columns.keys()) == {
        "id",
        "title",
        "created_at",
        "updated_at",
    }


def test_messages_columns_constraints_and_index() -> None:
    ddl = _ddl("messages")
    assert "conversation_id UNIQUEIDENTIFIER NOT NULL" in ddl
    assert "role NVARCHAR(20) NOT NULL" in ddl
    # NVARCHAR(max), never the deprecated NTEXT.
    assert "content NVARCHAR(max) NOT NULL" in ddl
    assert "citations NVARCHAR(max) NULL" in ddl
    assert "NTEXT" not in ddl
    assert "token_count INTEGER NULL" in ddl
    assert "CONSTRAINT ck_messages_role CHECK (role IN ('user', 'assistant'))" in ddl
    assert (
        "CONSTRAINT ck_messages_citations_json "
        "CHECK (citations IS NULL OR ISJSON(citations) = 1)" in ddl
    )
    assert (
        "CONSTRAINT fk_messages_conversation_id_conversations "
        "FOREIGN KEY(conversation_id) REFERENCES conversations (id)" in ddl
    )
    # NO ACTION: no cascade clause is emitted.
    assert "ON DELETE" not in ddl

    (index,) = Base.metadata.tables["messages"].indexes
    assert str(CreateIndex(index).compile(dialect=DIALECT)) == (
        "CREATE INDEX ix_messages_conversation_id ON messages (conversation_id, created_at)"
    )


def test_python_side_defaults() -> None:
    table = Base.metadata.tables["conversations"]
    assert table.c.title.default.arg == DEFAULT_TITLE == "New conversation"
    assert table.c.id.default is not None  # uuid4, generated by the app
    assert Base.metadata.tables["messages"].c.id.default is not None
    # Constructing models touches no database.
    conversation = Conversation(title="t")
    message = Message(conversation_id=None, role="user", content="q")
    assert conversation.title == "t"
    assert message.citations is None


@pytest.fixture()
def _restore_logging():
    """env.py applies alembic.ini's CLI logging via fileConfig; undo it afterwards."""
    root = logging.getLogger()
    saved = (root.level, list(root.handlers))
    yield
    root.setLevel(saved[0])
    root.handlers[:] = saved[1]
    for name in ("alembic", "sqlalchemy.engine"):
        logger = logging.getLogger(name)
        logger.handlers[:] = []
        logger.setLevel(logging.NOTSET)
        logger.propagate = True


@pytest.mark.usefixtures("_restore_logging")
def test_first_revision_creates_exactly_the_model_ddl(monkeypatch: pytest.MonkeyPatch) -> None:
    """Drift guard: the hand-written revision and the models render the same T-SQL."""

    def refuse(*args: object, **kwargs: object) -> None:
        raise AssertionError("offline mode must never connect")

    monkeypatch.setattr(pyodbc, "connect", refuse)
    monkeypatch.setenv("DATABASE_URL", TEST_URL)
    output = io.StringIO()
    command.upgrade(Config(str(INI), output_buffer=output, stdout=io.StringIO()), "head", sql=True)
    migration_sql = _normalise(output.getvalue())

    for name in ("conversations", "messages"):
        assert _normalise(_ddl(name)) in migration_sql, name
    for index in Base.metadata.tables["messages"].indexes:
        assert _normalise(str(CreateIndex(index).compile(dialect=DIALECT))) in migration_sql
