/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Health endpoint reporting observability state.
     */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Info
     * @description Consolidated status + version + runtime report for this service.
     *
     *     Extends the /health shape with the build version and runtime/system
     *     metadata. Reachable only via the BFF (web) on the internal network.
     */
    get: operations['info_info_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ping': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ping
     * @description Liveness greeting endpoint.
     */
    get: operations['ping_ping_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/conversations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List conversations, newest first */
    get: operations['list_conversations_v1_conversations_get'];
    put?: never;
    /** Start a conversation */
    post: operations['create_conversation_v1_conversations_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/conversations/{conversation_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a conversation with its messages */
    get: operations['get_conversation_v1_conversations__conversation_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/conversations/{conversation_id}/ask': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ask a question in a conversation */
    post: operations['ask_in_conversation_v1_conversations__conversation_id__ask_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/conversations/{conversation_id}/ask/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Ask a question in a conversation, streamed */
    post: operations['ask_in_conversation_stream_v1_conversations__conversation_id__ask_stream_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AskRequest */
    AskRequest: {
      /**
       * Question
       * @description 1–4000 characters after trimming; longer → 413.
       */
      question: string;
    };
    /** AskResponse */
    AskResponse: {
      /** Answer */
      answer: string;
      /**
       * Citations
       * @description The documents the answer drew on (ADR-0015).
       */
      citations: components['schemas']['Citation'][];
      /**
       * Message Id
       * Format: uuid
       * @description The stored assistant message.
       */
      message_id: string;
    };
    /** Citation */
    Citation: {
      /** Path */
      path: string;
      /** Title */
      title: string;
    };
    /** ConversationDetail */
    ConversationDetail: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Messages
       * @description Oldest first.
       */
      messages: components['schemas']['MessageOut'][];
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ConversationList */
    ConversationList: {
      /**
       * Count
       * @description Number of items returned (not a total).
       */
      count: number;
      /** Items */
      items: components['schemas']['ConversationSummary'][];
    };
    /** ConversationOut */
    ConversationOut: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ConversationSummary */
    ConversationSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Title */
      title: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** CreateConversation */
    CreateConversation: {
      /**
       * Title
       * @description Optional, at most 200 characters after trimming. Missing or blank → "New conversation"; the first question then replaces it (roadmap api 2.2).
       */
      title?: string | null;
    };
    /**
     * ErrorBody
     * @description The one error shape every api response uses.
     */
    ErrorBody: {
      /**
       * Error
       * @description Stable snake_case code, e.g. not_found, validation_error.
       */
      error: string;
      /**
       * Trace Id
       * @description The request's trace id — the same value as the x-trace-id header.
       */
      trace_id: string;
    };
    /** MessageOut */
    MessageOut: {
      /**
       * Citations
       * @description Assistant messages: the documents cited (ADR-0015).
       */
      citations?: components['schemas']['Citation'][] | null;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'user' | 'assistant';
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  info_info_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  ping_ping_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_conversations_v1_conversations_get: {
    parameters: {
      query?: {
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationList'];
        };
      };
      /** @description Validation failed (`validation_error`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Unhandled error (`internal_error`) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  create_conversation_v1_conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateConversation'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationOut'];
        };
      };
      /** @description Validation failed (`validation_error`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Unhandled error (`internal_error`) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  get_conversation_v1_conversations__conversation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConversationDetail'];
        };
      };
      /** @description Unknown conversation (`not_found`) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Validation failed (`validation_error`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Unhandled error (`internal_error`) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  ask_in_conversation_v1_conversations__conversation_id__ask_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AskRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AskResponse'];
        };
      };
      /** @description Unknown conversation (`not_found`) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Question too long (`payload_too_large`) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Validation failed (`validation_error`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Unhandled error (`internal_error`) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Model or search failed (`ai_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
  ask_in_conversation_stream_v1_conversations__conversation_id__ask_stream_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AskRequest'];
      };
    };
    responses: {
      /** @description SSE: `sources` → `token`* → `done`, or `error` after the first frame. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': unknown;
        };
      };
      /** @description Unknown conversation (`not_found`) */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Question too long (`payload_too_large`) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Validation failed (`validation_error`) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Unhandled error (`internal_error`) */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
      /** @description Failed before the first frame (`ai_unavailable`) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ErrorBody'];
        };
      };
    };
  };
}
